/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Account;
import db.tables.Payment;
import db.tables.records.AccountRecord;
import db.tables.records.PaymentRecord;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> PK_T_ACCOUNT = UniqueKeys0.PK_T_ACCOUNT;
    public static final UniqueKey<PaymentRecord> PK_T_PAYMENT = UniqueKeys0.PK_T_PAYMENT;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> PK_T_ACCOUNT = Internal.createUniqueKey(Account.ACCOUNT, "PK_T_ACCOUNT", Account.ACCOUNT.ID);
        public static final UniqueKey<PaymentRecord> PK_T_PAYMENT = Internal.createUniqueKey(Payment.PAYMENT, "PK_T_PAYMENT", Payment.PAYMENT.PAYMENT_ID);
    }
}
