/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Account;
import db.tables.Payment;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>PUBLIC.PAYMENT</code>.
     */
    public static final Payment PAYMENT = Payment.PAYMENT;
}
